include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Regras extras que eu sempre uso em projetos elite (2025)
    # always_specify_types: true # Removido: conflita com omit_local_variable_types
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    # prefer_relative_imports: true # Removido: conflita com always_use_package_imports
    avoid_relative_lib_imports: false
    lines_longer_than_80_chars: false # aceitável em Flutter
    avoid_print: true
    avoid_dynamic_calls: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: false
