include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Regras desabilitadas (muito restritivas para migração)
    always_specify_types: false # Muito verbose, Dart tem inferência forte
    require_trailing_commas: false # Formatter já cuida disso
    avoid_dynamic_calls: false # Necessário durante migração

    # Regras mantidas (importantes)
    prefer_single_quotes: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    # prefer_relative_imports: true # Removido: conflita com always_use_package_imports
    avoid_relative_lib_imports: false
    lines_longer_than_80_chars: false
    avoid_print: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: false
