// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps - PRODUCTION Environment.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Production Firebase project (to-sem-banda-83e19)
  // This is the current production project - keep these credentials
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_YOUR_PROD_ANDROID_API_KEY',
    appId: '1:YOUR_PROD_APP_ID:android:YOUR_PROD_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_PROD_SENDER_ID',
    projectId: 'to-sem-banda-83e19',
    storageBucket: 'to-sem-banda-83e19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_YOUR_PROD_IOS_API_KEY',
    appId: '1:YOUR_PROD_APP_ID:ios:YOUR_PROD_IOS_APP_ID',
    messagingSenderId: 'YOUR_PROD_SENDER_ID',
    projectId: 'to-sem-banda-83e19',
    storageBucket: 'to-sem-banda-83e19.appspot.com',
    iosBundleId: 'com.tosembanda.wegig',
  );
}
