// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps - DEV Environment.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your DEV Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QxHROqFRoIzCHBK_NFxu-GG6uMNS0uk',
    appId: '1:278498777601:android:e53cb79c055240be9ebe00',
    messagingSenderId: '278498777601',
    projectId: 'to-sem-banda-83e19',
    storageBucket: 'to-sem-banda-83e19.firebasestorage.app',
  );

  // Run: flutterfire configure --project=to-sem-banda-dev --out=lib/firebase_options_dev.dart

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_WwvD3nN-VJlMZf2L_BRpIx-ne3P_-0',
    appId: '1:278498777601:ios:cfb059150a3453319ebe00',
    messagingSenderId: '278498777601',
    projectId: 'to-sem-banda-83e19',
    storageBucket: 'to-sem-banda-83e19.firebasestorage.app',
    iosClientId: '278498777601-ejv3c0b9pb4fhft1i1ok276hrs05g3op.apps.googleusercontent.com',
    iosBundleId: 'com.tosembanda.wegig.dev',
  );

}